#!/usr/bin/env bash
# Threat Intel Aggregator — Summarize Script
# Reads /data/threat-intel-latest.json and outputs a markdown briefing

set -euo pipefail

INPUT="/data/threat-intel-latest.json"

if [[ ! -f "$INPUT" ]]; then
  echo "❌ No intel data found. Run fetch-intel.sh first." >&2
  exit 1
fi

TIMESTAMP=$(jq -r '.timestamp' "$INPUT")

cat <<EOF
# 🛡️ Threat Intelligence Briefing

**Generated:** $(date -u +"%Y-%m-%d %H:%M UTC")
**Data collected:** ${TIMESTAMP}
**Sources:** CISA KEV, NVD, URLhaus, ThreatFox

---

## 🔴 CISA Known Exploited Vulnerabilities (Recent)

EOF

# KEV entries
KEV_COUNT=$(jq '.cisa_kev | length' "$INPUT")
if [[ "$KEV_COUNT" -gt 0 ]]; then
  jq -r '.cisa_kev[] | "- **\(.cveID)** — \(.vendorProject) \(.product): \(.vulnerabilityName)\n  Added: \(.dateAdded) | Due: \(.dueDate)\n  \(.shortDescription)\n"' "$INPUT"
else
  echo "_No recent KEV entries._"
  echo
fi

cat <<EOF
## 🟠 Critical CVEs (CVSS ≥ 9.0)

EOF

# Critical CVEs
CRITICAL=$(jq '[.recent_cves[] | select(.cvss != null and .cvss >= 9)]' "$INPUT")
CRIT_COUNT=$(echo "$CRITICAL" | jq 'length')
if [[ "$CRIT_COUNT" -gt 0 ]]; then
  echo "$CRITICAL" | jq -r '.[] | "- **\(.id)** (CVSS: \(.cvss) \(.severity))\n  \(.description[:200])\n  Published: \(.published)\n"'
else
  echo "_No critical CVEs (CVSS ≥ 9.0) in current batch._"
  echo
fi

cat <<EOF
## 🟡 All Recent CVEs

EOF

jq -r '.recent_cves[:10][] | "- **\(.id)** — CVSS: \(.cvss // "N/A") | \(.description[:120])..."' "$INPUT" 2>/dev/null || echo "_No CVE data available._"
echo

cat <<EOF
## 🌐 Malicious URLs (URLhaus)

EOF

URL_COUNT=$(jq '.malicious_urls | length' "$INPUT")
if [[ "$URL_COUNT" -gt 0 ]]; then
  jq -r '.malicious_urls[:10][] | "- [\(.url_status)] \(.threat // "unknown") — `\(.url[:80])`  (\(.date_added))"' "$INPUT"
else
  echo "_No recent malicious URLs._"
fi
echo

cat <<EOF
## 🧬 Indicators of Compromise (ThreatFox)

EOF

IOC_COUNT=$(jq '.iocs | length' "$INPUT")
if [[ "$IOC_COUNT" -gt 0 ]]; then
  jq -r '.iocs[:10][] | "- **\(.malware)** [\(.threat_type)] — `\(.ioc)` (\(.ioc_type)) confidence: \(.confidence_level)%"' "$INPUT"
else
  echo "_No recent IOCs._"
fi

cat <<EOF

---

## 📊 Summary

| Feed | Count |
|------|-------|
| CISA KEV | ${KEV_COUNT} |
| Recent CVEs | $(jq '.recent_cves | length' "$INPUT") |
| Critical CVEs | ${CRIT_COUNT} |
| Malicious URLs | ${URL_COUNT} |
| IOCs | ${IOC_COUNT} |

---
*Report generated by Threat Intel Aggregator — Galahad Security Division*
EOF
